######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 13 14:41:40 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += grobLine.h widget.hpp
SOURCES += grobLine.cpp main.cpp widget.cpp
