######################################################################
# Automatically generated by qmake (2.01a) Wed Sep 14 16:48:15 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += grobLine.h widget.hpp
SOURCES += grobLine.cpp main.cpp widget.cpp
